name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

       - name: Install dependencies
         run: npm install
         working-directory: ./apps/frontend

       - name: Lint code
         run: npm run lint
         working-directory: ./apps/frontend

       - name: Run tests
         run: npm test -- --watchAll=false --coverage
         working-directory: ./apps/frontend

       - name: Build project
         run: npm run build
         working-directory: ./apps/frontend

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/frontend
          prod: true
